/* =========================================================
   Data proyek — dipakai bersama oleh index.html & projects.html
   Seluruh 33 entri dipertahankan dari sumber asli.
   ========================================================= */

const PROJECTS = [
  { id: 1, name: "UTA'45 Jakarta", category: "Website Utama",
    desc: "Website utama universitas — dikelola dan dioptimasi dari sisi Technical SEO, GA4 Analytics, dan performa halaman.",
    role: "WordPress · SEO & Analytics", metric: "Lighthouse 93/100",
    url: "https://www.uta45jakarta.ac.id/" },

  { id: 2, name: "UTA Bicara", category: "Humas & Media Center",
    desc: "Portal berita resmi, kegiatan kampus, dan publikasi media universitas.",
    role: "WordPress · SEO", metric: null,
    url: "https://utabicara.uta45jakarta.ac.id/" },

  { id: 3, name: "FEBIS", category: "FEBIS",
    desc: "Website utama Fakultas Ekonomi, Bisnis & Ilmu Sosial.",
    role: "WordPress · Technical SEO", metric: null,
    url: "https://febis.uta45jakarta.ac.id/" },
  { id: 4, name: "Administrasi Bisnis", category: "FEBIS",
    desc: "Website Program Studi Administrasi Bisnis.",
    role: "WordPress · SEO", metric: null,
    url: "http://administrasibisnis.uta45jakarta.ac.id/" },
  { id: 5, name: "Administrasi Publik", category: "FEBIS",
    desc: "Website Program Studi Administrasi Publik.",
    role: "WordPress · SEO", metric: null,
    url: "http://administrasipublik.uta45jakarta.ac.id/" },
  { id: 6, name: "Akuntansi", category: "FEBIS",
    desc: "Website Program Studi Akuntansi.",
    role: "WordPress · SEO", metric: null,
    url: "http://akuntansi.uta45jakarta.ac.id/" },
  { id: 7, name: "Bisnis Digital", category: "FEBIS",
    desc: "Website Program Studi Bisnis Digital.",
    role: "WordPress · SEO", metric: null,
    url: "http://bisnisdigital.uta45jakarta.ac.id/" },
  { id: 8, name: "Hubungan Internasional", category: "FEBIS",
    desc: "Website Program Studi Hubungan Internasional.",
    role: "WordPress · SEO", metric: null,
    url: "https://hubunganinternasional.uta45jakarta.ac.id/" },
  { id: 9, name: "Ilmu Komunikasi", category: "FEBIS",
    desc: "Website Program Studi Ilmu Komunikasi.",
    role: "WordPress · SEO", metric: null,
    url: "https://ilmukomunikasi.uta45jakarta.ac.id/" },
  { id: 10, name: "Ilmu Pemerintahan", category: "FEBIS",
    desc: "Website Program Studi Ilmu Pemerintahan.",
    role: "WordPress · SEO", metric: null,
    url: "https://pemerintahan.uta45jakarta.ac.id/" },
  { id: 11, name: "Manajemen", category: "FEBIS",
    desc: "Website Program Studi Manajemen.",
    role: "WordPress · SEO", metric: null,
    url: "https://manajemen.uta45jakarta.ac.id/" },

  { id: 12, name: "Farmasi", category: "Farmasi",
    desc: "Website utama Fakultas Farmasi.",
    role: "WordPress · Technical SEO", metric: null,
    url: "https://farmasi.uta45jakarta.ac.id/" },
  { id: 13, name: "Sarjana Farmasi", category: "Farmasi",
    desc: "Website Program Studi Sarjana Farmasi.",
    role: "WordPress · SEO", metric: null,
    url: "https://sarjanafarmasi.uta45jakarta.ac.id/" },
  { id: 14, name: "Magister Farmasi", category: "Farmasi",
    desc: "Website Program Studi Magister Farmasi.",
    role: "WordPress · SEO", metric: null,
    url: "https://magisterfarmasi.uta45jakarta.ac.id/" },
  { id: 15, name: "Apoteker", category: "Farmasi",
    desc: "Website Program Profesi Apoteker.",
    role: "WordPress · SEO", metric: null,
    url: "https://apoteker.uta45jakarta.ac.id/" },

  { id: 16, name: "Hukum", category: "Hukum",
    desc: "Website utama Fakultas Hukum.",
    role: "WordPress · Technical SEO", metric: null,
    url: "https://hukum.uta45jakarta.ac.id/" },
  { id: 17, name: "Sarjana Hukum", category: "Hukum",
    desc: "Website Program Studi Sarjana Hukum.",
    role: "WordPress · SEO", metric: null,
    url: "https://sarjanahukum.uta45jakarta.ac.id/" },
  { id: 18, name: "Magister Hukum", category: "Hukum",
    desc: "Website Program Studi Magister Hukum.",
    role: "WordPress · SEO", metric: null,
    url: "https://magisterhukum.uta45jakarta.ac.id/" },
  { id: 19, name: "Doktor Hukum", category: "Hukum",
    desc: "Website Program Studi Doktor Hukum.",
    role: "WordPress · SEO", metric: null,
    url: "https://doktorhukum.uta45jakarta.ac.id/" },

  { id: 20, name: "Teknik", category: "Teknik",
    desc: "Website utama Fakultas Teknik.",
    role: "WordPress · Technical SEO", metric: null,
    url: "https://teknik.uta45jakarta.ac.id/" },
  { id: 21, name: "Teknik Elektro", category: "Teknik",
    desc: "Website Program Studi Teknik Elektro.",
    role: "WordPress · SEO", metric: null,
    url: "https://elektro.uta45jakarta.ac.id/" },
  { id: 22, name: "Teknik Mesin", category: "Teknik",
    desc: "Website Program Studi Teknik Mesin.",
    role: "WordPress · SEO", metric: null,
    url: "https://mesin.uta45jakarta.ac.id/" },
  { id: 23, name: "Teknik Sipil", category: "Teknik",
    desc: "Website Program Studi Teknik Sipil.",
    role: "WordPress · SEO", metric: null,
    url: "https://sipil.uta45jakarta.ac.id/" },
  { id: 24, name: "Informatika", category: "Teknik",
    desc: "Website Program Studi Informatika.",
    role: "WordPress · SEO", metric: null,
    url: "https://informatika.uta45jakarta.ac.id/" },

  { id: 25, name: "SIMKER", category: "Aplikasi",
    desc: "Sistem Informasi Kerjasama institusi (MoU, MoA, IA) pada 3 tingkat: Program Studi, Fakultas, dan Universitas.",
    role: "Full-Stack · CodeIgniter 3", metric: null,
    url: "https://simker.uta45jakarta.ac.id/" },
  { id: 26, name: "SIMLITABMAS", category: "Aplikasi",
    desc: "Sistem Informasi Penelitian dan Pengabdian Masyarakat, dari pengajuan oleh dosen & mahasiswa hingga pendanaan LPPM.",
    role: "Full-Stack · CodeIgniter 3", metric: null,
    url: "https://simlitabmas.uta45jakarta.ac.id/" },
  { id: 27, name: "Journal UTA45", category: "Aplikasi",
    desc: "Platform jurnal ilmiah universitas berbasis Open Journal Systems.",
    role: "OJS 2 · Database Mgmt", metric: null,
    url: "https://journal.uta45jakarta.ac.id/" },
  { id: 28, name: "Perpustakaan", category: "Aplikasi",
    desc: "Sistem informasi perpustakaan digital.",
    role: "SLiMS 9 Bulian", metric: null,
    url: "https://lib.uta45jakarta.ac.id/" },
  { id: 29, name: "Cloud UTA45", category: "Aplikasi",
    desc: "Platform penyimpanan & kolaborasi cloud internal.",
    role: "Nextcloud Administration", metric: null,
    url: "https://cloud.uta45jakarta.ac.id/" },
  { id: 30, name: "Repository UTA45", category: "Aplikasi",
    desc: "Repositori karya ilmiah & institusi.",
    role: "EPrints 3 Administration", metric: null,
    url: "https://repository.uta45jakarta.ac.id/" },
  { id: 31, name: "Layanan UTA45", category: "Aplikasi",
    desc: "Sistem layanan helpdesk & ticketing mahasiswa.",
    role: "HESK Ticketing System", metric: null,
    url: "https://layanan.uta45jakarta.ac.id/" },
  { id: 32, name: "GA4 Analytics Dashboard", category: "Aplikasi",
    desc: "Dashboard otomatisasi agregasi data traffic & user behavior dari 23 properti GA4 secara terpusat.",
    role: "Google Apps Script · GA4", metric: "23 properti",
    url: null },
  { id: 33, name: "LPMI", category: "Aplikasi",
    desc: "Website dan portal sistem Lembaga Penjaminan Mutu Internal.",
    role: "WordPress · Portal Mgmt", metric: null,
    url: "https://lpmi.uta45jakarta.ac.id/" },
];

const CATEGORY_ORDER = [
  "Website Utama",
  "Humas & Media Center",
  "FEBIS",
  "Farmasi",
  "Hukum",
  "Teknik",
  "Aplikasi",
];
